env:
  browser: true
  es2021: true
extends:
  - next/core-web-vitals
  - plugin:react/recommended
  - google
  - prettier
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules: { "require-jsdoc": "off", "react/prop-types": "off" }
